# Generated by Django 3.2.9 on 2021-11-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('n', 'Новость'), ('a', 'Статья')], default='a', max_length=1),
        ),
    ]
